// Authoritative facility + open-requisition data extracted from the company's
// master recruiting workbook (AMA_Recruiting_Master.xlsx): 95 facilities across
// SNF / outpatient clinic / lab / hospital / operations, and the 87 open
// requisitions (the real openings, with priority, recruiter, and pay range).
// Drives the local-workspace seed for facilities and coverage needs.

export interface MasterFacility {
  id: string
  name: string
  type: string
  network: string
  entity: string
  region: string | null
  state: string | null
  city: string | null
  current_census: number | null
  total_census: number | null
  assigned_physician: string | null
  assigned_np: string | null
}

export interface MasterReq {
  req_id: string
  type: string
  entity: string
  state: string | null
  region: string | null
  city: string | null
  facility_id: string
  facility_name: string
  position: string
  category: string
  openings_count: number
  priority: string
  status: string
  rate_min: number | null
  rate_max: number | null
  rate_unit: string | null
  recruiter: string | null
  hiring_manager: string | null
}

export const MASTER_FACILITIES: MasterFacility[] = [
  { id: "FAC-0001", name: "BERNARD CARE CENTER (STL)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "St Louis", state: "MO", city: null, current_census: 89, total_census: 132, assigned_physician: "DR ALMASALMEH", assigned_np: "CANDACE KIRKPATRICK" },
  { id: "FAC-0002", name: "BRIDGEWOOD HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Kansas City MO", state: "MO", city: null, current_census: 137, total_census: 138, assigned_physician: "DR SUTHERLAND", assigned_np: "KOURTNEY HALFORD" },
  { id: "FAC-0003", name: "BROOKFIELD HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "North Central", state: "MO", city: null, current_census: 4, total_census: 32, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0004", name: "BRUNSWICK HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "North Central", state: "MO", city: null, current_census: 7, total_census: 26, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0005", name: "CARRIE ELLINGSON GEITNER HEALTH CARE (STL)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "St Louis", state: "MO", city: null, current_census: 31, total_census: 92, assigned_physician: "DR ALMASALMEH", assigned_np: null },
  { id: "FAC-0006", name: "CASSVILLE HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "West Rural MO", state: "MO", city: null, current_census: 0, total_census: 41, assigned_physician: "DR MANZER", assigned_np: "CRYSTAL DYER" },
  { id: "FAC-0007", name: "CEDARGATE HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "SE MO", state: "MO", city: null, current_census: 11, total_census: 59, assigned_physician: "DR ARSHAD", assigned_np: "FRANK VILLAMAYOR" },
  { id: "FAC-0008", name: "CHARITON PARK HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Moberly (NE of STL)", state: "MO", city: null, current_census: 114, total_census: 114, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0009", name: "CRESTWOOD HEALTH CARE CENTER (STL)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "St Louis", state: "MO", city: null, current_census: 88, total_census: 141, assigned_physician: "DR ALMASALMEH", assigned_np: "CANDACE KIRKPATRICK" },
  { id: "FAC-0010", name: "EASTON HEALTH CARE CENTER (KANSAS)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "KC Kansas", state: "KS", city: null, current_census: 2, total_census: 40, assigned_physician: "DR MANZER", assigned_np: "CRYSTAL DYER" },
  { id: "FAC-0011", name: "EASTVIEW MANOR CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "North Central", state: "MO", city: null, current_census: 80, total_census: 84, assigned_physician: "DR SUTHERLAND", assigned_np: "SARA KOENEMANN" },
  { id: "FAC-0012", name: "EDGEWOOD MANOR HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Kansas City MO", state: "MO", city: null, current_census: 47, total_census: 79, assigned_physician: "DR SUTHERLAND", assigned_np: "KOURTNEY HALFORD" },
  { id: "FAC-0013", name: "FAIR VIEW HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Sedalia", state: "MO", city: null, current_census: 63, total_census: 66, assigned_physician: "DR SUTHERLAND", assigned_np: "BONNIE REID" },
  { id: "FAC-0014", name: "FOUR SEASONS LIVING CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Sedalia", state: "MO", city: null, current_census: 224, total_census: 228, assigned_physician: "DR SUTHERLAND", assigned_np: "BONNIE REID" },
  { id: "FAC-0015", name: "GRAND MANOR HEALTH CARE CENTER (STL)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "St Louis", state: "MO", city: null, current_census: 52, total_census: 110, assigned_physician: "DR ALMASALMEH", assigned_np: null },
  { id: "FAC-0016", name: "GREENVILLE HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "SE MO", state: "MO", city: null, current_census: 14, total_census: 58, assigned_physician: "DR ARSHAD", assigned_np: "FRANK VILLAMAYOR" },
  { id: "FAC-0017", name: "GREGORY RIDGE HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Kansas City MO", state: "MO", city: null, current_census: 104, total_census: 104, assigned_physician: "DR SUTHERLAND", assigned_np: "SARA KOENEMANN" },
  { id: "FAC-0018", name: "HERITAGE CARE CENTER OF BERKELEY (STL)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "St Louis", state: "MO", city: null, current_census: 67, total_census: 110, assigned_physician: "DR ALMASALMEH", assigned_np: "CANDACE KIRKPATRICK" },
  { id: "FAC-0019", name: "HIDDEN LAKE HEALTH CARE CENTER (STL)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "St Louis", state: "MO", city: null, current_census: 6, total_census: 34, assigned_physician: "DR ALMASALMEH", assigned_np: null },
  { id: "FAC-0020", name: "HILLSIDE HEALTH CARE CENTER (STL)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "St Louis", state: "MO", city: null, current_census: 0, total_census: 152, assigned_physician: "DR ALMASALMEH", assigned_np: null },
  { id: "FAC-0021", name: "HOLTON HEALTH CARE CENTER (KANSAS)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "KC Kansas", state: "KS", city: null, current_census: 0, total_census: 33, assigned_physician: "DR MANZER", assigned_np: "CRYSTAL DYER" },
  { id: "FAC-0022", name: "LEGENDARY HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Sedalia", state: "MO", city: null, current_census: 18, total_census: 38, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0023", name: "LEVERING", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: 17, total_census: 18, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0024", name: "MILAN HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: 23, total_census: 97, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0025", name: "NATHAN RICHARD HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "West Rural MO", state: "MO", city: null, current_census: 59, total_census: 60, assigned_physician: "DR MANZER", assigned_np: "KOURTNEY HALFORD" },
  { id: "FAC-0026", name: "NICKS HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Kansas City MO", state: "MO", city: null, current_census: 66, total_census: 66, assigned_physician: "DR MANZER", assigned_np: "SARA KOENEMANN" },
  { id: "FAC-0027", name: "NORTH VILLAGE PARK", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Moberly (NE of STL)", state: "MO", city: null, current_census: 172, total_census: 172, assigned_physician: "DR ALMASALMEH", assigned_np: null },
  { id: "FAC-0028", name: "NORTONVILLE (KANSAS)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "KC Kansas", state: "KS", city: null, current_census: 0, total_census: 34, assigned_physician: "DR MANZER", assigned_np: "CRYSTAL DYER" },
  { id: "FAC-0029", name: "ODESSA HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Kansas City MO", state: "MO", city: null, current_census: 9, total_census: 60, assigned_physician: "DR SUTHERLAND", assigned_np: "KOURTNEY HALFORD" },
  { id: "FAC-0030", name: "PARKWAY HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Kansas City MO", state: "MO", city: null, current_census: 58, total_census: 58, assigned_physician: "DR SUTHERLAND", assigned_np: "SARA KOENEMANN" },
  { id: "FAC-0031", name: "PETTIS COUNTY ASSISTED LIVING", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Sedalia", state: "MO", city: null, current_census: 111, total_census: 114, assigned_physician: "DR SUTHERLAND", assigned_np: "BONNIE REID" },
  { id: "FAC-0032", name: "PORTAGEVILLE HEALTHCARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "SE MO", state: "MO", city: null, current_census: 57, total_census: 57, assigned_physician: "DR ARSHAD", assigned_np: "FAAIZA ARSHAD" },
  { id: "FAC-0033", name: "REST HAVEN HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Sedalia", state: "MO", city: null, current_census: 61, total_census: 61, assigned_physician: "DR SUTHERLAND", assigned_np: "BONNIE REID" },
  { id: "FAC-0034", name: "SARCOXIE HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "West Rural MO", state: "MO", city: null, current_census: 35, total_census: 39, assigned_physician: "DR MANZER", assigned_np: "CRYSTAL DYER" },
  { id: "FAC-0035", name: "SOUTH COUNTY HEALTH CARE CENTER (STL)", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "St Louis", state: "MO", city: null, current_census: 25, total_census: 88, assigned_physician: "DR ALMASALMEH", assigned_np: null },
  { id: "FAC-0036", name: "ST ELIZABETH HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "Middle MO", state: "MO", city: null, current_census: 59, total_census: 60, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0037", name: "STONECREST HEALTHCARE", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "SE MO", state: "MO", city: null, current_census: 56, total_census: 56, assigned_physician: "DR ALMASALMEH", assigned_np: "FRANK VILLAMAYOR" },
  { id: "FAC-0038", name: "WELLSVILLE HEALTH CARE CENTER", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "North Central", state: "MO", city: null, current_census: 67, total_census: 67, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0039", name: "WESTVIEW NURSING HOME", type: "SNF", network: "Reliant Homes", entity: "AMMO", region: "North Central", state: "MO", city: null, current_census: 52, total_census: 59, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0040", name: "BRENT B TINNIN", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 38, assigned_physician: "DR ARSHAD", assigned_np: "FRANK VILLAMAYOR" },
  { id: "FAC-0041", name: "HERITAGE KENNETT", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 10, assigned_physician: "DR ARSHAD", assigned_np: "FAAIZA ARSHAD" },
  { id: "FAC-0042", name: "HUNTER ACRES", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 11, assigned_physician: "DR ARSHAD", assigned_np: "FAAIZA ARSHAD" },
  { id: "FAC-0043", name: "LOVING ARMS", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 12, assigned_physician: "DR SUTHERLAND", assigned_np: "BONNIE REID" },
  { id: "FAC-0044", name: "MARI DE VILLE (STL)", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 4, assigned_physician: "DR ALMASALMEH", assigned_np: null },
  { id: "FAC-0045", name: "NHC KENNETT", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 16, assigned_physician: "DR ARSHAD", assigned_np: "FAAIZA ARSHAD" },
  { id: "FAC-0046", name: "RIVER OAKS", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 63, assigned_physician: "DR ARSHAD", assigned_np: "FAAIZA ARSHAD" },
  { id: "FAC-0047", name: "SALT RIVER", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 39, assigned_physician: "DR ALMASALMEH", assigned_np: "THOMAS SMITH" },
  { id: "FAC-0048", name: "SOUTH GATE", type: "SNF", network: "Not Reliant Homes", entity: "AMMO", region: null, state: "MO", city: null, current_census: null, total_census: 61, assigned_physician: "DR ARSHAD", assigned_np: "FAAIZA ARSHAD" },
  { id: "FAC-0049", name: "Scott City Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Scott City", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0050", name: "Big Springs Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMTX", region: null, state: "TX", city: "Big Springs", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0051", name: "St. PetersFlorissant Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "St. PetersFlorissant", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0052", name: "Kennett Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Kennett", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0053", name: "Sealy Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMTX", region: null, state: "TX", city: "Sealy", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0054", name: "Kennet Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Kennet", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0055", name: "Kennet Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Kennet", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0056", name: "Phoenix Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMAZ", region: null, state: "AZ", city: "Phoenix", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0057", name: "??? Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: null, city: "???", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0058", name: "Hopsital/Clinic", type: "Hospital", network: "AMA", entity: "AMA-AR", region: null, state: "AR", city: "Blytheville", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0059", name: "Union City Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMA-GA", region: null, state: "GA", city: "Union City", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0060", name: "SNF (Macon GA)", type: "SNF", network: "AMA", entity: "AMA-GA", region: null, state: "GA", city: "Macon/Warner Robins", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0061", name: "Macon Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Macon", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0062", name: "Riverdale/Union City Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMA-GA", region: null, state: "GA", city: "Riverdale/Union City", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0063", name: "Riverdale Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMA-GA", region: null, state: "GA", city: "Riverdale", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0064", name: "Florissant Primary Care", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Florissant", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0065", name: "Bevier/Macon Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Bevier/Macon", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0066", name: "Carthage Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Carthage", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0067", name: "Chesterfield Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Chesterfield", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0068", name: "St. Peters Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "St. Peters", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0069", name: "Galena Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMA-KS", region: null, state: "KS", city: "Galena", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0070", name: "Kansas City Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Kansas City", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0071", name: "Macon Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMA-GA", region: null, state: "GA", city: "Macon", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0072", name: "SNF (Macon GA)", type: "SNF", network: "AMA", entity: "AMA-GA", region: null, state: "GA", city: "Macon", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0073", name: "Sedalia Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Sedalia", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0074", name: "Operations (STL)", type: "Operations", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "STL", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0075", name: "Operations (St. Louis)", type: "Operations", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "St. Louis", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0076", name: "Chesterfield Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Chesterfield", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0077", name: "Kansas City Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Kansas City", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0078", name: "Gideon Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Gideon", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0079", name: "KennethMO Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: null, city: "KennethMO", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0080", name: "Hayti Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Hayti", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0081", name: "ATL (Lower Atlanta) Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: null, city: "ATL (Lower Atlanta)", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0082", name: "(Sealy) Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMTX", region: null, state: "TX", city: "(Sealy)", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0083", name: "Corporate", type: "Operations", network: "AMA", entity: "AMMO", region: null, state: null, city: "SEMO", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0084", name: "WMO (Carthage) Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: null, city: "WMO (Carthage)", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0085", name: "Macon Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMA-GA", region: null, state: "GA", city: "Macon", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0086", name: "STL Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "STL", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0087", name: "Stl Healthcare group", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Chesterfield", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0088", name: "Carthage Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Carthage", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0089", name: "AMM Medical Tiko 304", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Kennett", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0090", name: "Hayti Medical & Diagnostic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Hayti", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0091", name: "901 McPhereson", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Kennett", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0092", name: "Scott City Medical Clinic", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Scott City", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0093", name: "SEMO AMA", type: "Outpatient Clinic", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Poplar Bluff", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0094", name: "AMA LAB (Columbia)", type: "Lab", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Columbia", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
  { id: "FAC-0095", name: "AMA LAB (Carthage)", type: "Lab", network: "AMA", entity: "AMMO", region: null, state: "MO", city: "Carthage", current_census: null, total_census: null, assigned_physician: null, assigned_np: null },
]

export const MASTER_REQS: MasterReq[] = [
  { req_id: "REQ-00002", type: "Outpatient", entity: "AMTX", state: "TX", region: null, city: "Big Springs, TX", facility_id: "FAC-0050", facility_name: "clinic", position: "MRI tech", category: "Clinical - Tech", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Alicia", hiring_manager: "Mike McCallum" },
  { req_id: "REQ-00003", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "St. Peters, MOFlorissant, MO", facility_id: "FAC-0064", facility_name: "Clinic", position: "Ultrasound Tech", category: "Clinical - Tech", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Anthony", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00004", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennett MO", facility_id: "FAC-0052", facility_name: "Clinic", position: "PA/FNP", category: "Provider - Advanced Practice", openings_count: 1, priority: "High", status: "Open", rate_min: 130000, rate_max: 130000, rate_unit: "Annual", recruiter: "Alicia", hiring_manager: "Dr. Arshad-" },
  { req_id: "REQ-00005", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennett MO", facility_id: "FAC-0052", facility_name: "Clinic", position: "Physician Pain Management", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Alicia", hiring_manager: null },
  { req_id: "REQ-00008", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennet MO", facility_id: "FAC-0054", facility_name: "Clinic", position: "Physician - Pediatrics", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Open", rate_min: 250000, rate_max: 300000, rate_unit: "Annual", recruiter: "Alicia", hiring_manager: "Dr. Arshad" },
  { req_id: "REQ-00009", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennet, MO", facility_id: "FAC-0054", facility_name: "Clinic", position: "Physician - Podiatrist", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Alicia", hiring_manager: null },
  { req_id: "REQ-00011", type: "Outpatient", entity: "AMAZ", state: "AZ", region: null, city: "Phoenix, AZ", facility_id: "FAC-0056", facility_name: "Clinic", position: "Physician - Interventional Radiologist", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Alicia", hiring_manager: "Send to Rob" },
  { req_id: "REQ-00012", type: "Outpatient", entity: "AMAZ", state: "AZ", region: null, city: "Phoenix, AZ", facility_id: "FAC-0056", facility_name: "Clinic", position: "Physician - Invasive Cardiologist", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Alicia", hiring_manager: "Send to Rob" },
  { req_id: "REQ-00013", type: "Outpatient", entity: "AMAZ", state: "AZ", region: null, city: "Phoenix, AZ", facility_id: "FAC-0056", facility_name: "Clinic", position: "Physician - Nuerologist", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Alicia", hiring_manager: "Send to Rob" },
  { req_id: "REQ-00014", type: "Outpatient", entity: "AMMO", state: null, region: null, city: "???", facility_id: "FAC-0057", facility_name: "Clinic", position: "PA/FNP Urgent Care", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: 130000, rate_max: 130000, rate_unit: "Annual", recruiter: "Alicia", hiring_manager: "Kaitlin Skinner" },
  { req_id: "REQ-00016", type: "Outpatient", entity: "AMA-GA", state: "GA", region: null, city: "Union City GA", facility_id: "FAC-0059", facility_name: "Clinic", position: "PA/FNP (Speaks Gujurati/Hindi)", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Background Check", rate_min: 130000, rate_max: 130000, rate_unit: "Annual", recruiter: "Alicia", hiring_manager: "Dr. Jayesh" },
  { req_id: "REQ-00017", type: "Outpatient", entity: "AMA-GA", state: "GA", region: null, city: "Macon/Warner Robins GA", facility_id: "FAC-0060", facility_name: "SNF", position: "PA/FNP SNF", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: 130000, rate_max: 130000, rate_unit: "Annual", recruiter: "Alicia", hiring_manager: "Kailin Skinner resumes" },
  { req_id: "REQ-00018", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Macon MO", facility_id: "FAC-0061", facility_name: "Clinic", position: "PA/FNP", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: 120000, rate_max: 120000, rate_unit: "Annual", recruiter: "Alicia", hiring_manager: "Dr. Arshad" },
  { req_id: "REQ-00019", type: "Outpatient", entity: "AMA-GA", state: "GA", region: null, city: "Riverdale/Union City, GA", facility_id: "FAC-0059", facility_name: "Clinic", position: "Practice Manager", category: "Operations - Leadership", openings_count: 1, priority: "Medium", status: "Open", rate_min: 45000, rate_max: 50000, rate_unit: "Annual", recruiter: "Anthony", hiring_manager: "Kaitlin Skinner resumes" },
  { req_id: "REQ-00023", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Florissant , MO", facility_id: "FAC-0064", facility_name: "Florissant Primary Care", position: "MA", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: 17, rate_max: 18, rate_unit: "Hourly", recruiter: "Anthony", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00024", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Bevier, MO/Macon, MO", facility_id: "FAC-0061", facility_name: "Clinic", position: "MA/Receptionist", category: "Admin - Front Office", openings_count: 1, priority: "High", status: "Open", rate_min: 16, rate_max: 17, rate_unit: "Hourly", recruiter: "Judi", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00025", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Carthage MO", facility_id: "FAC-0066", facility_name: "Clinic", position: "CT Tech", category: "Clinical - Tech", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Judi", hiring_manager: "Amber Hunter" },
  { req_id: "REQ-00027", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Carthage MO", facility_id: "FAC-0066", facility_name: "Clinic", position: "MA full time", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: 16, rate_max: 17, rate_unit: "Hourly", recruiter: "Judi", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00028", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Chesterfield, MO", facility_id: "FAC-0067", facility_name: "Clinic", position: "Physician - Family Care", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Open", rate_min: 250000, rate_max: 300000, rate_unit: "Annual", recruiter: "Judi", hiring_manager: "Dr. Arshad" },
  { req_id: "REQ-00029", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Chesterfield, MO", facility_id: "FAC-0067", facility_name: "Clinic", position: "NP/PA GYN (young vibrant)", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Judi", hiring_manager: null },
  { req_id: "REQ-00030", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "St. Peters, MO", facility_id: "FAC-0068", facility_name: "Clinic", position: "MA/Receptionist", category: "Admin - Front Office", openings_count: 1, priority: "Medium", status: "Open", rate_min: 17, rate_max: 18, rate_unit: "Hourly", recruiter: "Judi", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00031", type: "Outpatient", entity: "AMA-KS", state: "KS", region: null, city: "Galena, KS", facility_id: "FAC-0069", facility_name: "Clinic", position: "MA/Receptionist Full time", category: "Admin - Front Office", openings_count: 1, priority: "Medium", status: "Open", rate_min: 17, rate_max: 19, rate_unit: "Hourly", recruiter: "Judi", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00032", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kansas City, MO", facility_id: "FAC-0070", facility_name: "Clinic", position: "Physician - Psychiatrist", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Judi", hiring_manager: null },
  { req_id: "REQ-00033", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennet MO", facility_id: "FAC-0054", facility_name: "Clinic", position: "LPN Peds", category: "Clinical - Nursing", openings_count: 1, priority: "Medium", status: "Open", rate_min: 22, rate_max: 22, rate_unit: "Hourly", recruiter: "Judi", hiring_manager: "Tiifany Jones" },
  { req_id: "REQ-00035", type: "Outpatient", entity: "AMA-GA", state: "GA", region: null, city: "Macon, GA", facility_id: "FAC-0061", facility_name: "Clinic", position: "MA full time", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: 16, rate_max: 16, rate_unit: "Hourly", recruiter: "Judi", hiring_manager: "Kaitlin Skinner" },
  { req_id: "REQ-00037", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Sedalia MO", facility_id: "FAC-0073", facility_name: "Clinic", position: "Scribe (Dr. Sutherland)", category: "Admin - Front Office", openings_count: 1, priority: "Medium", status: "Open", rate_min: 19, rate_max: 21, rate_unit: "Hourly", recruiter: "Judi", hiring_manager: "Shelly Bradford" },
  { req_id: "REQ-00039", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "St. Louis, MO", facility_id: "FAC-0075", facility_name: "Operations", position: "Senior Accountant", category: "Operations - Leadership", openings_count: 1, priority: "Medium", status: "Open", rate_min: 75000, rate_max: 85000, rate_unit: "Annual", recruiter: "Rob", hiring_manager: "Nish/Brandon RCMC" },
  { req_id: "REQ-00056", type: "Outpatient", entity: "AMA-KS", state: "KS", region: null, city: "Galena, KS", facility_id: "FAC-0069", facility_name: "Clinic", position: "Physician Interventional Pain MD", category: "Provider - Physician", openings_count: 1, priority: "Medium", status: "Background Check", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Kayla", hiring_manager: "Kayla Manley" },
  { req_id: "REQ-00057", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennet, MO", facility_id: "FAC-0054", facility_name: "Clinic", position: "MA 901", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: 18, rate_max: 18, rate_unit: "Hourly", recruiter: "Anthony", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00058", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennet, MO", facility_id: "FAC-0054", facility_name: "Clinic", position: "LTC Scheduler", category: "Admin - Front Office", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Anthony", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00061", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Scott City MO", facility_id: "FAC-0049", facility_name: "Clinic", position: "Physician - Primary Care", category: "Provider - Physician", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Anthony", hiring_manager: "Megan Mikel" },
  { req_id: "REQ-00063", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Chesterfield, MO", facility_id: "FAC-0087", facility_name: "Stl Healthcare group", position: "Receptionist", category: "Admin - Front Office", openings_count: 1, priority: "High", status: "Open", rate_min: 17, rate_max: 18, rate_unit: "Hourly", recruiter: "Anthony", hiring_manager: "Kailin" },
  { req_id: "REQ-00064", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Carthage, MO", facility_id: "FAC-0066", facility_name: "Clinic", position: "X-Ray tech", category: "Clinical - Tech", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Kayla", hiring_manager: "Kayla Manley" },
  { req_id: "REQ-00065", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Carthage MO", facility_id: "FAC-0066", facility_name: "Clinic", position: "MA full time", category: "Clinical - MA", openings_count: 1, priority: "High", status: "Open", rate_min: 25, rate_max: 25, rate_unit: "Hourly", recruiter: "Kayla", hiring_manager: "Kayla Manley" },
  { req_id: "REQ-00066", type: "Outpatient", entity: "AMA-GA", state: "GA", region: null, city: "Macon, GA", facility_id: "FAC-0061", facility_name: "Clinic", position: "RN (clinical trainer - OP exp.)", category: "Clinical - Nursing", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Kayla", hiring_manager: "Kayla Manley" },
  { req_id: "REQ-00067", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennett, MO", facility_id: "FAC-0089", facility_name: "AMM Medical Tiko 304", position: "MA", category: "Clinical - MA", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Kayla", hiring_manager: "Kayla Manley" },
  { req_id: "REQ-00068", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennett, MO", facility_id: "FAC-0089", facility_name: "AMM Medical Tiko 304", position: "LPN", category: "Clinical - Nursing", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: null, hiring_manager: null },
  { req_id: "REQ-00069", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Hayti MO", facility_id: "FAC-0090", facility_name: "Hayti Medical & Diagnostic", position: "LPN", category: "Clinical - Nursing", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: null, hiring_manager: null },
  { req_id: "REQ-00070", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Kennett, MO", facility_id: "FAC-0091", facility_name: "901 McPhereson", position: "LPN", category: "Clinical - Nursing", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: null, hiring_manager: null },
  { req_id: "REQ-00071", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Scott City MO", facility_id: "FAC-0092", facility_name: "Scott City Medical Clinic", position: "MA", category: "Clinical - MA", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: null, hiring_manager: null },
  { req_id: "REQ-00072", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Poplar Bluff, MO", facility_id: "FAC-0093", facility_name: "SEMO AMA", position: "Rural Health Clinic Director", category: "Operations - Leadership", openings_count: 1, priority: "High", status: "Open", rate_min: 60000, rate_max: 60000, rate_unit: "Annual", recruiter: null, hiring_manager: null },
  { req_id: "REQ-00073", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Columbia, MO", facility_id: "FAC-0094", facility_name: "AMA LAB", position: "Phlebotomist/Courier", category: "Clinical - Tech", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: null, hiring_manager: null },
  { req_id: "REQ-00074", type: "Outpatient", entity: "AMMO", state: "MO", region: null, city: "Carthage, MO", facility_id: "FAC-0095", facility_name: "AMA LAB", position: "Phlebotomist/Courier", category: "Clinical - Tech", openings_count: 1, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: null, hiring_manager: null },
  { req_id: "REQ-00075", type: "SNF", entity: "AMMO", state: "MO", region: "Kansas City MO", city: "Kansas City MO", facility_id: "FAC-0002", facility_name: "BRIDGEWOOD HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 2.75, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00076", type: "SNF", entity: "AMMO", state: "MO", region: "Kansas City MO", city: "Kansas City MO", facility_id: "FAC-0012", facility_name: "EDGEWOOD MANOR HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00077", type: "SNF", entity: "AMMO", state: "MO", region: "Kansas City MO", city: "Kansas City MO", facility_id: "FAC-0017", facility_name: "GREGORY RIDGE HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00078", type: "SNF", entity: "AMMO", state: "MO", region: "Kansas City MO", city: "Kansas City MO", facility_id: "FAC-0026", facility_name: "NICKS HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00079", type: "SNF", entity: "AMMO", state: "MO", region: "Kansas City MO", city: "Kansas City MO", facility_id: "FAC-0029", facility_name: "ODESSA HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00080", type: "SNF", entity: "AMMO", state: "MO", region: "Kansas City MO", city: "Kansas City MO", facility_id: "FAC-0030", facility_name: "PARKWAY HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00081", type: "SNF", entity: "AMMO", state: "MO", region: "North Central", city: "North Central", facility_id: "FAC-0011", facility_name: "EASTVIEW MANOR CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 2, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00082", type: "SNF", entity: "AMMO", state: "MO", region: "North Central", city: "North Central", facility_id: "FAC-0024", facility_name: "MILAN HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 2, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00083", type: "SNF", entity: "AMA-KS", state: "KS", region: "KC Kansas", city: "KC Kansas", facility_id: "FAC-0010", facility_name: "EASTON HEALTH CARE CENTER (KANSAS)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00084", type: "SNF", entity: "AMA-KS", state: "KS", region: "KC Kansas", city: "KC Kansas", facility_id: "FAC-0021", facility_name: "HOLTON HEALTH CARE CENTER (KANSAS)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00085", type: "SNF", entity: "AMA-KS", state: "KS", region: "KC Kansas", city: "KC Kansas", facility_id: "FAC-0028", facility_name: "NORTONVILLE (KANSAS)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00086", type: "SNF", entity: "AMMO", state: "MO", region: "Middle MO", city: "Middle MO", facility_id: "FAC-0036", facility_name: "ST ELIZABETH HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00087", type: "SNF", entity: "AMMO", state: "MO", region: "Moberly (NE of STL)", city: "Moberly (NE of STL)", facility_id: "FAC-0008", facility_name: "CHARITON PARK HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 2, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00088", type: "SNF", entity: "AMMO", state: "MO", region: "Moberly (NE of STL)", city: "Moberly (NE of STL)", facility_id: "FAC-0027", facility_name: "NORTH VILLAGE PARK", position: "Medical Assistant", category: "Clinical - MA", openings_count: 3, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00089", type: "SNF", entity: "AMMO", state: "MO", region: "North Central", city: "North Central", facility_id: "FAC-0003", facility_name: "BROOKFIELD HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00090", type: "SNF", entity: "AMMO", state: "MO", region: "North Central", city: "North Central", facility_id: "FAC-0004", facility_name: "BRUNSWICK HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00091", type: "SNF", entity: "AMMO", state: "MO", region: "North Central", city: "North Central", facility_id: "FAC-0038", facility_name: "WELLSVILLE HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00092", type: "SNF", entity: "AMMO", state: "MO", region: "North Central", city: "North Central", facility_id: "FAC-0039", facility_name: "WESTVIEW NURSING HOME", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00093", type: "SNF", entity: "AMMO", state: "MO", region: "SE MO", city: "SE MO", facility_id: "FAC-0007", facility_name: "CEDARGATE HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00094", type: "SNF", entity: "AMMO", state: "MO", region: "SE MO", city: "SE MO", facility_id: "FAC-0016", facility_name: "GREENVILLE HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00095", type: "SNF", entity: "AMMO", state: "MO", region: "SE MO", city: "SE MO", facility_id: "FAC-0032", facility_name: "PORTAGEVILLE HEALTHCARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00096", type: "SNF", entity: "AMMO", state: "MO", region: "SE MO", city: "SE MO", facility_id: "FAC-0037", facility_name: "STONECREST HEALTHCARE", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00097", type: "SNF", entity: "AMMO", state: "MO", region: "Sedalia", city: "Sedalia", facility_id: "FAC-0013", facility_name: "FAIR VIEW HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00098", type: "SNF", entity: "AMMO", state: "MO", region: "Sedalia", city: "Sedalia", facility_id: "FAC-0014", facility_name: "FOUR SEASONS LIVING CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 4.5, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00099", type: "SNF", entity: "AMMO", state: "MO", region: "Sedalia", city: "Sedalia", facility_id: "FAC-0022", facility_name: "LEGENDARY HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00100", type: "SNF", entity: "AMMO", state: "MO", region: "Sedalia", city: "Sedalia", facility_id: "FAC-0031", facility_name: "PETTIS COUNTY ASSISTED LIVING", position: "Medical Assistant", category: "Clinical - MA", openings_count: 2, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00101", type: "SNF", entity: "AMMO", state: "MO", region: "Sedalia", city: "Sedalia", facility_id: "FAC-0033", facility_name: "REST HAVEN HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00103", type: "SNF", entity: "AMMO", state: "MO", region: "St Louis", city: "St Louis", facility_id: "FAC-0005", facility_name: "CARRIE ELLINGSON GEITNER HEALTH CARE (STL)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00104", type: "SNF", entity: "AMMO", state: "MO", region: "St Louis", city: "St Louis", facility_id: "FAC-0009", facility_name: "CRESTWOOD HEALTH CARE CENTER (STL)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 3, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00105", type: "SNF", entity: "AMMO", state: "MO", region: "St Louis", city: "St Louis", facility_id: "FAC-0015", facility_name: "GRAND MANOR HEALTH CARE CENTER (STL)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00106", type: "SNF", entity: "AMMO", state: "MO", region: "St Louis", city: "St Louis", facility_id: "FAC-0018", facility_name: "HERITAGE CARE CENTER OF BERKELEY (STL)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00107", type: "SNF", entity: "AMMO", state: "MO", region: "St Louis", city: "St Louis", facility_id: "FAC-0019", facility_name: "HIDDEN LAKE HEALTH CARE CENTER (STL)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00108", type: "SNF", entity: "AMMO", state: "MO", region: "St Louis", city: "St Louis", facility_id: "FAC-0020", facility_name: "HILLSIDE HEALTH CARE CENTER (STL)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 3, priority: "High", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00109", type: "SNF", entity: "AMMO", state: "MO", region: "St Louis", city: "St Louis", facility_id: "FAC-0035", facility_name: "SOUTH COUNTY HEALTH CARE CENTER (STL)", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00110", type: "SNF", entity: "AMMO", state: "MO", region: "West Rural MO", city: "West Rural MO", facility_id: "FAC-0006", facility_name: "CASSVILLE HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00111", type: "SNF", entity: "AMMO", state: "MO", region: "West Rural MO", city: "West Rural MO", facility_id: "FAC-0025", facility_name: "NATHAN RICHARD HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00112", type: "SNF", entity: "AMMO", state: "MO", region: "West Rural MO", city: "West Rural MO", facility_id: "FAC-0034", facility_name: "SARCOXIE HEALTH CARE CENTER", position: "Medical Assistant", category: "Clinical - MA", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00113", type: "SNF", entity: "AMMO", state: "MO", region: "KC Kansas", city: "Kansas", facility_id: "FAC-0021", facility_name: "HOLTON HEALTH CARE CENTER (KANSAS)", position: "NP/PA", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00114", type: "SNF", entity: "AMMO", state: "MO", region: "Middle MO", city: "St. Elizabeth, MO, 65075", facility_id: "FAC-0036", facility_name: "ST ELIZABETH HEALTH CARE CENTER", position: "NP/PA", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00115", type: "SNF", entity: "AMMO", state: "MO", region: "North Central", city: "Macon central", facility_id: "FAC-0004", facility_name: "BRUNSWICK HEALTH CARE CENTER", position: "NP/PA", category: "Provider - Advanced Practice", openings_count: 2, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00116", type: "SNF", entity: "AMMO", state: "MO", region: "North Central", city: "Milan, MO", facility_id: "FAC-0024", facility_name: "MILAN HEALTH CARE CENTER", position: "NP/PA", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00117", type: "SNF", entity: "AMMO", state: "MO", region: "SE MO", city: "SE MO", facility_id: "FAC-0016", facility_name: "GREENVILLE HEALTH CARE CENTER", position: "NP/PA", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00118", type: "SNF", entity: "AMMO", state: "MO", region: "Sedalia", city: "Sedalia", facility_id: "FAC-0022", facility_name: "LEGENDARY HEALTH CARE CENTER", position: "NP/PA", category: "Provider - Advanced Practice", openings_count: 1, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
  { req_id: "REQ-00119", type: "SNF", entity: "AMMO", state: "MO", region: "St Louis", city: "St Louis", facility_id: "FAC-0009", facility_name: "CRESTWOOD HEALTH CARE CENTER (STL)", position: "NP/PA", category: "Provider - Advanced Practice", openings_count: 2, priority: "Medium", status: "Open", rate_min: null, rate_max: null, rate_unit: null, recruiter: "Corby", hiring_manager: "Corby" },
]
