-- ============================================================================
-- Clinilytics ATS v2 — screening → matching context columns
-- ----------------------------------------------------------------------------
-- The matching feedback loop folds analyzed AI screenings (and the comms log)
-- into a denormalized candidate summary that ranking blends in. v2 `candidates`
-- needs the same two columns the old schema used. Idempotent; apply after
-- 10_migrate_from_legacy.sql (or anytime after 06). These are regenerated by the
-- app's refreshCandidateContext(), so the migration may leave them null.
-- ============================================================================
alter table public.candidates add column if not exists screening_summary text;
alter table public.candidates add column if not exists last_screened_at  timestamptz;
create index if not exists idx_cand_last_screened on public.candidates (last_screened_at);
